import type { TemplateDefinition } from "@/lib/templates";

export type TemplateDirection = {
  structure: string;
  design: string;
  appearance: string;
  typography: string;
  palette: string;
  motifs: string;
};

const DIRECTIONS: Array<{ match: RegExp; direction: TemplateDirection }> = [
  {
    match: /xiguiane|african/i,
    direction: {
      structure: "Capa cerimonial + história + família + programa + RSVP",
      design: "Editorial africano contemporâneo com blocos assimétricos e selos",
      appearance: "Capulana, textura artesanal, terra e verde, acabamento premium",
      typography: "Serif elegante + sans limpa para informação",
      palette: "Terracota, areia, verde profundo e bronze",
      motifs: "Padrões têxteis, molduras, selos e geometrias inspiradas na herança moçambicana",
    },
  },
  {
    match: /garden|botanical|floral|romantic/i,
    direction: {
      structure: "Capa leve + história + galeria + programa + RSVP + mensagens",
      design: "Composição orgânica, respirada e centrada no casal",
      appearance: "Papel claro, aguarela, flores e folhagem delicada",
      typography: "Serif editorial + script pontual",
      palette: "Marfim, blush, verde folha e rosa antigo",
      motifs: "Ramos, flores, manchas de aguarela e linhas orgânicas",
    },
  },
  {
    match: /royal|baroque|nikah|oriental|heritage/i,
    direction: {
      structure: "Capa de impacto + cerimónia + família + programa + confirmação",
      design: "Composição simétrica, molduras e hierarquia cerimonial",
      appearance: "Luxo clássico, ornamentado e inspirado em papelaria física",
      typography: "Serif de alto contraste + pequenos textos em caixa alta",
      palette: "Jóias profundas, marfim e dourado antigo",
      motifs: "Molduras, arabescos, geometrias e ornamentos cerimoniais",
    },
  },
  {
    match: /film-noir-motion/i,
    direction: {
      structure: "Capa em vídeo + manifesto + casal + momentos + programa + RSVP",
      design: "Cinematografia editorial com hero em ecrã inteiro e transições de filme",
      appearance: "Preto carvão, grão de película, fotografia dramática e detalhes dourados",
      typography: "Serif cinematográfica + sans condensada",
      palette: "Carvão, marfim, dourado queimado e preto",
      motifs: "Frames de filme, números de cena, linhas de timeline e créditos finais",
    },
  },
  {
    match: /editorial-magazine/i,
    direction: {
      structure: "Capa editorial + índice + história + galeria + programa + RSVP",
      design: "Revista de moda com colunas, títulos grandes e fotografia recortada",
      appearance: "Luxo contemporâneo, branco quente e fotografia protagonista",
      typography: "Serif fashion + sans editorial",
      palette: "Marfim, preto, taupe e bronze",
      motifs: "Números gigantes, filetes, legendas e composição assimétrica",
    },
  },
  {
    match: /pearl-garden/i,
    direction: {
      structure: "Capa botânica + carta + casal + jardim de memórias + programa + RSVP",
      design: "Composição orgânica assimétrica com molduras de pérola",
      appearance: "Romântico, luminoso e delicado sem parecer infantil",
      typography: "Serif elegante + script pontual",
      palette: "Pérola, blush, verde sálvia e champagne",
      motifs: "Pérolas, flores finas, folhas e manchas suaves",
    },
  },
  {
    match: /capulana-contemporary/i,
    direction: {
      structure: "Capa têxtil + família + história + cerimónias + programa + RSVP",
      design: "Editorial moçambicano contemporâneo com módulos têxteis e diagonais",
      appearance: "Capulana sofisticada, textura artesanal e fotografia de grande escala",
      typography: "Serif forte + sans geométrica",
      palette: "Terracota, verde profundo, areia, azul petróleo e bronze",
      motifs: "Grafismos têxteis, selos, diagonais e linhas de costura",
    },
  },
  {
    match: /celestial-ivory/i,
    direction: {
      structure: "Capa celestial + mensagem + casal + constelação + programa + RSVP",
      design: "Minimalismo de luxo com mapa estelar e muito espaço negativo",
      appearance: "Marfim, dourado e céu profundo em pequenos pontos de contraste",
      typography: "Serif refinada + sans microtipográfica",
      palette: "Marfim, dourado, preto e azul-noite",
      motifs: "Constelações, órbitas, pontos de luz e linhas finíssimas",
    },
  },
  {
    match: /coastal-blue/i,
    direction: {
      structure: "Capa fotográfica + destino + casal + agenda + galeria + RSVP",
      design: "Destination editorial com fotografia panorâmica e blocos fluidos",
      appearance: "Fresco, elegante e solar",
      typography: "Serif leve + sans humanista",
      palette: "Azul oceano, areia, branco quente e dourado suave",
      motifs: "Ondas abstratas, linhas costeiras e coordenadas",
    },
  },
  {
    match: /minimal|editorial|cinematic/i,
    direction: {
      structure: "Capa editorial + mensagem + momentos + programa + RSVP",
      design: "Grid, espaço negativo e fotografia como elemento principal",
      appearance: "Galeria de moda, silenciosa, sofisticada e contemporânea",
      typography: "Serif editorial grande + sans geométrica",
      palette: "Neutros, preto, branco, vinho ou azul profundo",
      motifs: "Linhas finas, números editoriais, cortes fotográficos e microtipografia",
    },
  },
  {
    match: /boho|mediterranean|tropical/i,
    direction: {
      structure: "Capa fotográfica + história + local + programa + galeria + RSVP",
      design: "Blocos descontraídos, fotografia ampla e detalhes artesanais",
      appearance: "Destino, natureza, calor e textura sem perder sofisticação",
      typography: "Serif suave + sans humanista",
      palette: "Areia, terracota, azul costeiro, verde e pôr do sol",
      motifs: "Texturas naturais, folhas, linhas desenhadas e formas orgânicas",
    },
  },
  {
    match: /vintage|traditional|classic|european/i,
    direction: {
      structure: "Convite clássico + família + cerimónia + receção + confirmação",
      design: "Papelaria tradicional com hierarquia clara e molduras discretas",
      appearance: "Convite físico premium traduzido para o digital",
      typography: "Serif clássica + small caps",
      palette: "Marfim, creme, castanho, bronze e dourado suave",
      motifs: "Molduras, filetes, monogramas e selos",
    },
  },
];

const TEMPLATE_DIRECTION_OVERRIDES: Record<string, Partial<TemplateDirection>> = {
  "editorial-cinema": {
      structure: "Capa cinematográfica + palavra + casal + história + agenda + RSVP + créditos",
      design: "Filme editorial com capítulos, cortes fotográficos e final de créditos",
      appearance: "Carvão, marfim e fotografia em ecrã largo",
      typography: "Serif de cinema + sans condensada",
      palette: "Preto, marfim, bronze e cinza grafite",
      motifs: "Capítulos, frames, números de cena e barras de película",
    },
    "ivory-portrait": {
      structure: "Capa retrato + carta + casal + galeria + programa + RSVP",
      design: "Retrato central com muito espaço negativo e leitura de papel fino",
      appearance: "Marfim, fotografia suave e detalhes mínimos",
      typography: "Serif elegante + sans leve",
      palette: "Marfim, taupe, preto suave e champagne",
      motifs: "Molduras ovais, filetes e legendas pequenas",
    },
    "modern-olive": {
      structure: "Capa lateral + história + casal + local + agenda + galeria + RSVP",
      design: "Editorial oliva com módulos assimétricos e fotografia documental",
      appearance: "Natural, arquitectónico e contemporâneo",
      typography: "Serif moderna + grotesk",
      palette: "Oliva, areia, creme e bronze",
      motifs: "Blocos, coordenadas e linhas de orientação",
    },
    "rose-atelier": {
      structure: "Capa de atelier + carta + casal + memórias + programa + RSVP",
      design: "Moda romântica com recortes fotográficos e blocos de carta",
      appearance: "Blush, vinho suave, papel e fotografia de retrato",
      typography: "Serif fashion + sans editorial",
      palette: "Rosa antigo, creme, vinho e champagne",
      motifs: "Passpartout, molduras e legendas de galeria",
    },
    "mozambique-luxe": {
      structure: "Capa cerimonial + famílias + história + rituais + programa + RSVP",
      design: "Luxo moçambicano contemporâneo com tecido e fotografia de família",
      appearance: "Terra, verde profundo, bronze e textura artesanal",
      typography: "Serif forte + sans geométrica",
      palette: "Terracota, verde, areia e bronze",
      motifs: "Capulana, selos, linhas de costura e módulos cerimoniais",
    },
    "sunset-destination": {
      structure: "Capa panorâmica + destino + casal + agenda + dress code + galeria + RSVP",
      design: "Destination wedding com fotografia ampla e transições de horizonte",
      appearance: "Quente, solar e sofisticado",
      typography: "Serif leve + sans humanista",
      palette: "Terracota, coral, areia, azul profundo",
      motifs: "Horizonte, coordenadas e linhas de viagem",
    },
    "black-paper": {
      structure: "Capa preta + manifesto + casal + programa + RSVP + galeria",
      design: "Papel preto editorial com capítulos curtos e tipografia monumental",
      appearance: "Silencioso, táctil e muito contrastado",
      typography: "Sans grotesk grande + serif pontual",
      palette: "Preto, osso e bronze",
      motifs: "Numeração, regras finas e notas editoriais",
    },
    "pearl-editorial": {
      structure: "Capa pérola + carta + casal + galeria + agenda + RSVP + mensagens",
      design: "Pérola contemporânea com ritmo de revista e fotografia em molduras suaves",
      appearance: "Luminoso, refinado e orgânico",
      typography: "Serif elegante + sans microtipográfica",
      palette: "Pérola, blush, sálvia e champagne",
      motifs: "Anéis, molduras suaves e filetes",
    },
  
    "golden-classic": { structure: "Capa formal + mensagem + casal + cerimónia + receção + RSVP", design: "Convite clássico de luxo com centro tipográfico e moldura fina", motifs: "Monograma, filetes dourados e selo central" },
    "classic-ivory": { structure: "Capa papel + família + mensagem + programa + local + RSVP", design: "Papelaria marfim com leitura vertical e blocos de convite", motifs: "Filetes, relevo visual e pequenos separadores" },
    "emerald-elegante": { structure: "Capa lateral + palavra + casal + programa + localização + RSVP", design: "Minimalismo verde profundo com alinhamento editorial lateral", motifs: "Linhas botânicas discretas e marcador de secção" },
    "minimalist-brown": { structure: "Capa esquerda + história + galeria + agenda + confirmação", design: "Editorial quente com blocos rectangulares e fotografia dominante", motifs: "Margens amplas, números e papel natural" },
    "minimalist-burgundy": { structure: "Capa tipográfica + mensagem + história + galeria + RSVP", design: "Minimalismo bordô com eixo vertical e contraste alto", motifs: "Regra vertical, pequenos capítulos e microtipografia" },
    "minimalist-lavender": { structure: "Capa orgânica + casal + momentos + galeria + RSVP", design: "Minimalismo suave com cantos assimétricos e ritmo leve", motifs: "Arcos, curvas e detalhes lavanda" },
    "minimalist-white": { structure: "Capa limpa + palavra + casal + galeria + programa + RSVP", design: "Galeria branca com muito espaço negativo e tipografia protagonista", motifs: "Filetes mínimos, numeração e fotografia sem moldura" },
    "minimalist-black": { structure: "Capa escura + manifesto + história + galeria + RSVP", design: "Editorial preto com título monumental e alinhamento baixo", motifs: "Microtexto, números grandes e blocos de contraste" },
    "midnight-blue": { structure: "Capa cinematográfica + countdown + história + programa + RSVP", design: "Azul-noite imersivo com leitura de filme e baixa luz", motifs: "Linha temporal, estrelas discretas e coordenadas" },
    "sapphire-editorial": { structure: "Capa editorial + casal + história + galeria vertical + programa + RSVP", design: "Revista azul safira com coluna fotográfica assimétrica", motifs: "Legendas, filetes e cortes fotográficos" },
    "editorial-dark": { structure: "Capa escura + índice + história + momentos + galeria + RSVP", design: "Editorial nocturno com blocos de conteúdo alinhados à esquerda", motifs: "Índice, capítulos e números de página" },
    "cinematic-charcoal": { structure: "Capa full-screen + história + momentos + galeria + agenda + RSVP", design: "Narrativa cinematográfica em carvão com fotografia em primeiro plano", motifs: "Frames, créditos e marcações de cena" },
    "baroque-gold": { structure: "Capa ornamentada + palavra + família + cerimónia + receção + RSVP", design: "Composição palaciana simétrica com moldura dupla", motifs: "Arabescos, molduras e selo dourado" },
    "royal-emerald": { structure: "Capa emoldurada + bênção + casal + família + programa + RSVP", design: "Cerimonial verde joia com eixo central e cartões nobres", motifs: "Brasão, filetes dourados e medalhão" },
    "royal-burgundy": { structure: "Capa cerimonial + palavra + família + programa + galeria + RSVP", design: "Bordô imperial com secções compactas e detalhes de gala", motifs: "Molduras, medalhões e divisores dourados" },
    "royal-sapphire": { structure: "Capa safira + mensagem + casal + programa + galeria + RSVP", design: "Luxo azul profundo com fotografia circular e moldura aberta", motifs: "Diamantes, molduras finas e pequenos emblemas" },
    "royal-black-gold": { structure: "Capa preta + selo + família + história + cerimónia + RSVP", design: "Convite de gala preto e dourado com dupla moldura", motifs: "Moldura dupla, selo e assinatura central" },
    "romantic-rose": { structure: "Capa floral + carta + casal + história + galeria + RSVP", design: "Romântico rosado com composição oval e foco no casal", motifs: "Arcos, pétalas e linhas suaves" },
    "romantic-champagne": { structure: "Capa champagne + casal + história + programa + galeria + RSVP", design: "Gala luminosa com retrato circular e cartões elegantes", motifs: "Medalhões, champagne e pequenos brilhos" },
    "garden-green": { structure: "Capa botânica + palavra + casal + galeria + história + programa + RSVP", design: "Jardim verde com imagens em ritmos alternados", motifs: "Folhas, ramos e recortes assimétricos" },
    "garden-blue": { structure: "Capa fresca + casal + galeria + história + local + RSVP", design: "Jardim azul com alinhamento lateral e formas fluidas", motifs: "Folhagem azul, arcos e linhas orgânicas" },
    "garden-ivory": { structure: "Capa marfim + carta + história + casal + galeria + RSVP", design: "Botânico luminoso com secções amplas e composição central", motifs: "Folhas finas, papel e molduras suaves" },
    "boho-sand": { structure: "Capa fotográfica + história + casal + local + dress code + RSVP", design: "Boho editorial com blocos de areia e cantos desencontrados", motifs: "Textura natural, arcos e linhas desenhadas" },
    "boho-rose": { structure: "Capa aguarela + história + galeria + casal + programa + RSVP", design: "Boho floral com imagens sobrepostas e curvas orgânicas", motifs: "Aguarela, pinceladas e formas artesanais" },
    "vintage-cream": { structure: "Capa postal + família + história + cerimónia + receção + RSVP", design: "Convite vintage com aparência de papel impresso", motifs: "Carimbo, moldura, filetes e textura de papel" },
    "european-ivory": { structure: "Capa europeia + família + mensagem + programa + local + RSVP", design: "Papelaria europeia minimal com composição rigorosamente centrada", motifs: "Small caps, filetes e monograma" },
    "mediterranean-blue": { structure: "Capa destino + local + casal + galeria + agenda + RSVP", design: "Destination wedding azul com fotografia ampla e blocos fluidos", motifs: "Coordenadas, ondas e linhas costeiras" },
    "sicilian-terracotta": { structure: "Capa terracota + história + casal + mesa + local + RSVP", design: "Siciliano solar com blocos quentes e fotografia documental", motifs: "Azulejo, terracota e formas geométricas" },
    "oriental-red": { structure: "Capa cerimonial + bênção + família + programa + receção + RSVP", design: "Heritage vermelho com simetria e molduras de inspiração oriental", motifs: "Geometria, medalhão e dourado" },
    "oriental-green": { structure: "Capa verde + palavra + casal + família + programa + RSVP", design: "Heritage verde com módulos simétricos e detalhes botânicos", motifs: "Arabescos, folhas e molduras" },
    "oriental-blue": { structure: "Capa porcelana + casal + história + programa + galeria + RSVP", design: "Heritage azul inspirado em porcelana e painéis", motifs: "Moldura azul, medalhão e padrões lineares" },
    "nikah-emerald": { structure: "Capa cerimonial + bênção + família + agenda + localização + RSVP", design: "Nikah verde joia com eixo central e leitura ritual", motifs: "Arcos, geometria islâmica e medalhão" },
    "traditional-bronze": { structure: "Capa papel + família + cerimónia + receção + programa + RSVP", design: "Tradicional bronze com sensação de convite físico premium", motifs: "Moldura, selo, filetes e bronze" },
    "tropical-green": { structure: "Capa tropical + história + casal + galeria + programa + RSVP", design: "Botânico tropical com fotografia alternada e ritmo vertical", motifs: "Folhagem ampla, recortes e curvas" },
    "tropical-sunset": { structure: "Capa pôr do sol + casal + história + local + galeria + RSVP", design: "Destination tropical com abertura fotográfica e alinhamento baixo", motifs: "Gradientes quentes, horizonte e formas solares" },
    "floral-pearl": { structure: "Capa pérola + carta + casal + jardim de memórias + RSVP", design: "Floral de luxo com composição perolada e molduras orgânicas", motifs: "Pérolas, flores finas e medalhões" },
    "african-heritage": { structure: "Capa cerimonial + família + história + momentos + programa + RSVP", design: "Herança africana contemporânea com módulos têxteis e selos", motifs: "Padrões, diagonais, selos e textura artesanal" },
    "xiguiane-tradicional": { structure: "Capa xiguiane + famílias + lobolo + cerimónias + programa + RSVP", design: "Convite moçambicano tradicional com foco em família e ritual", motifs: "Capulana, selos, molduras e grafismos locais" },
    "film-noir-motion": { structure: "Capa vídeo + manifesto + casal + momentos + programa + RSVP", design: "Filme de autor com hero em ecrã inteiro e cortes de narrativa", motifs: "Frames, timeline, créditos e números de cena" },
    "editorial-magazine": { structure: "Capa revista + índice + história + galeria + agenda + RSVP", design: "Fashion editorial com colunas, fotografia recortada e títulos gigantes", motifs: "Issue numbers, legendas e regras tipográficas" },
    "pearl-garden": { structure: "Capa jardim + carta + casal + memórias + programa + RSVP", design: "Jardim de luxo com molduras peroladas e composição assimétrica", motifs: "Pérolas, flores finas e anéis orgânicos" },
    "capulana-contemporary": { structure: "Capa têxtil + família + história + momentos + cerimónias + RSVP", design: "Editorial moçambicano contemporâneo com diagonais e módulos de tecido", motifs: "Capulana, costura, selos e padrões geométricos" },
    "celestial-ivory": { structure: "Capa celestial + palavra + countdown + casal + constelação + RSVP", design: "Luxury minimal com mapa estelar e espaço negativo", motifs: "Órbitas, constelações e microestrelas" },
    "coastal-blue": { structure: "Capa destino + localização + casal + galeria + agenda + RSVP", design: "Coastal editorial com fotografia panorâmica e ritmo de viagem", motifs: "Ondas, coordenadas e linhas de costa" },
    "aquarela-botanica": { structure: "Capa aguarela + palavra + casal + história + galeria + programa + RSVP", design: "Botânico pintado à mão com camadas de aguarela e fotografia suave", motifs: "Manchas de tinta, folhas, flores e pinceladas" },

  "golden-classic": { structure: "Capa formal + mensagem + casal + cerimónia + receção + RSVP", design: "Convite clássico de luxo com centro tipográfico e moldura fina", motifs: "Monograma, filetes dourados e selo central" },
  "classic-ivory": { structure: "Capa papel + família + mensagem + programa + local + RSVP", design: "Papelaria marfim com leitura vertical e blocos de convite", motifs: "Filetes, relevo visual e pequenos separadores" },
  "emerald-elegante": { structure: "Capa lateral + palavra + casal + programa + localização + RSVP", design: "Minimalismo verde profundo com alinhamento editorial lateral", motifs: "Linhas botânicas discretas e marcador de secção" },
  "minimalist-brown": { structure: "Capa esquerda + história + galeria + agenda + confirmação", design: "Editorial quente com blocos rectangulares e fotografia dominante", motifs: "Margens amplas, números e papel natural" },
  "minimalist-burgundy": { structure: "Capa tipográfica + mensagem + história + galeria + RSVP", design: "Minimalismo bordô com eixo vertical e contraste alto", motifs: "Regra vertical, pequenos capítulos e microtipografia" },
  "minimalist-lavender": { structure: "Capa orgânica + casal + momentos + galeria + RSVP", design: "Minimalismo suave com cantos assimétricos e ritmo leve", motifs: "Arcos, curvas e detalhes lavanda" },
  "minimalist-white": { structure: "Capa limpa + palavra + casal + galeria + programa + RSVP", design: "Galeria branca com muito espaço negativo e tipografia protagonista", motifs: "Filetes mínimos, numeração e fotografia sem moldura" },
  "minimalist-black": { structure: "Capa escura + manifesto + história + galeria + RSVP", design: "Editorial preto com título monumental e alinhamento baixo", motifs: "Microtexto, números grandes e blocos de contraste" },
  "midnight-blue": { structure: "Capa cinematográfica + countdown + história + programa + RSVP", design: "Azul-noite imersivo com leitura de filme e baixa luz", motifs: "Linha temporal, estrelas discretas e coordenadas" },
  "sapphire-editorial": { structure: "Capa editorial + casal + história + galeria vertical + programa + RSVP", design: "Revista azul safira com coluna fotográfica assimétrica", motifs: "Legendas, filetes e cortes fotográficos" },
  "editorial-dark": { structure: "Capa escura + índice + história + momentos + galeria + RSVP", design: "Editorial nocturno com blocos de conteúdo alinhados à esquerda", motifs: "Índice, capítulos e números de página" },
  "cinematic-charcoal": { structure: "Capa full-screen + história + momentos + galeria + agenda + RSVP", design: "Narrativa cinematográfica em carvão com fotografia em primeiro plano", motifs: "Frames, créditos e marcações de cena" },
  "baroque-gold": { structure: "Capa ornamentada + palavra + família + cerimónia + receção + RSVP", design: "Composição palaciana simétrica com moldura dupla", motifs: "Arabescos, molduras e selo dourado" },
  "royal-emerald": { structure: "Capa emoldurada + bênção + casal + família + programa + RSVP", design: "Cerimonial verde joia com eixo central e cartões nobres", motifs: "Brasão, filetes dourados e medalhão" },
  "royal-burgundy": { structure: "Capa cerimonial + palavra + família + programa + galeria + RSVP", design: "Bordô imperial com secções compactas e detalhes de gala", motifs: "Molduras, medalhões e divisores dourados" },
  "royal-sapphire": { structure: "Capa safira + mensagem + casal + programa + galeria + RSVP", design: "Luxo azul profundo com fotografia circular e moldura aberta", motifs: "Diamantes, molduras finas e pequenos emblemas" },
  "royal-black-gold": { structure: "Capa preta + selo + família + história + cerimónia + RSVP", design: "Convite de gala preto e dourado com dupla moldura", motifs: "Moldura dupla, selo e assinatura central" },
  "romantic-rose": { structure: "Capa floral + carta + casal + história + galeria + RSVP", design: "Romântico rosado com composição oval e foco no casal", motifs: "Arcos, pétalas e linhas suaves" },
  "romantic-champagne": { structure: "Capa champagne + casal + história + programa + galeria + RSVP", design: "Gala luminosa com retrato circular e cartões elegantes", motifs: "Medalhões, champagne e pequenos brilhos" },
  "garden-green": { structure: "Capa botânica + palavra + casal + galeria + história + programa + RSVP", design: "Jardim verde com imagens em ritmos alternados", motifs: "Folhas, ramos e recortes assimétricos" },
  "garden-blue": { structure: "Capa fresca + casal + galeria + história + local + RSVP", design: "Jardim azul com alinhamento lateral e formas fluidas", motifs: "Folhagem azul, arcos e linhas orgânicas" },
  "garden-ivory": { structure: "Capa marfim + carta + história + casal + galeria + RSVP", design: "Botânico luminoso com secções amplas e composição central", motifs: "Folhas finas, papel e molduras suaves" },
  "boho-sand": { structure: "Capa fotográfica + história + casal + local + dress code + RSVP", design: "Boho editorial com blocos de areia e cantos desencontrados", motifs: "Textura natural, arcos e linhas desenhadas" },
  "boho-rose": { structure: "Capa aguarela + história + galeria + casal + programa + RSVP", design: "Boho floral com imagens sobrepostas e curvas orgânicas", motifs: "Aguarela, pinceladas e formas artesanais" },
  "vintage-cream": { structure: "Capa postal + família + história + cerimónia + receção + RSVP", design: "Convite vintage com aparência de papel impresso", motifs: "Carimbo, moldura, filetes e textura de papel" },
  "european-ivory": { structure: "Capa europeia + família + mensagem + programa + local + RSVP", design: "Papelaria europeia minimal com composição rigorosamente centrada", motifs: "Small caps, filetes e monograma" },
  "mediterranean-blue": { structure: "Capa destino + local + casal + galeria + agenda + RSVP", design: "Destination wedding azul com fotografia ampla e blocos fluidos", motifs: "Coordenadas, ondas e linhas costeiras" },
  "sicilian-terracotta": { structure: "Capa terracota + história + casal + mesa + local + RSVP", design: "Siciliano solar com blocos quentes e fotografia documental", motifs: "Azulejo, terracota e formas geométricas" },
  "oriental-red": { structure: "Capa cerimonial + bênção + família + programa + receção + RSVP", design: "Heritage vermelho com simetria e molduras de inspiração oriental", motifs: "Geometria, medalhão e dourado" },
  "oriental-green": { structure: "Capa verde + palavra + casal + família + programa + RSVP", design: "Heritage verde com módulos simétricos e detalhes botânicos", motifs: "Arabescos, folhas e molduras" },
  "oriental-blue": { structure: "Capa porcelana + casal + história + programa + galeria + RSVP", design: "Heritage azul inspirado em porcelana e painéis", motifs: "Moldura azul, medalhão e padrões lineares" },
  "nikah-emerald": { structure: "Capa cerimonial + bênção + família + agenda + localização + RSVP", design: "Nikah verde joia com eixo central e leitura ritual", motifs: "Arcos, geometria islâmica e medalhão" },
  "traditional-bronze": { structure: "Capa papel + família + cerimónia + receção + programa + RSVP", design: "Tradicional bronze com sensação de convite físico premium", motifs: "Moldura, selo, filetes e bronze" },
  "tropical-green": { structure: "Capa tropical + história + casal + galeria + programa + RSVP", design: "Botânico tropical com fotografia alternada e ritmo vertical", motifs: "Folhagem ampla, recortes e curvas" },
  "tropical-sunset": { structure: "Capa pôr do sol + casal + história + local + galeria + RSVP", design: "Destination tropical com abertura fotográfica e alinhamento baixo", motifs: "Gradientes quentes, horizonte e formas solares" },
  "floral-pearl": { structure: "Capa pérola + carta + casal + jardim de memórias + RSVP", design: "Floral de luxo com composição perolada e molduras orgânicas", motifs: "Pérolas, flores finas e medalhões" },
  "african-heritage": { structure: "Capa cerimonial + família + história + momentos + programa + RSVP", design: "Herança africana contemporânea com módulos têxteis e selos", motifs: "Padrões, diagonais, selos e textura artesanal" },
  "xiguiane-tradicional": { structure: "Capa xiguiane + famílias + lobolo + cerimónias + programa + RSVP", design: "Convite moçambicano tradicional com foco em família e ritual", motifs: "Capulana, selos, molduras e grafismos locais" },
  "film-noir-motion": { structure: "Capa vídeo + manifesto + casal + momentos + programa + RSVP", design: "Filme de autor com hero em ecrã inteiro e cortes de narrativa", motifs: "Frames, timeline, créditos e números de cena" },
  "editorial-magazine": { structure: "Capa revista + índice + história + galeria + agenda + RSVP", design: "Fashion editorial com colunas, fotografia recortada e títulos gigantes", motifs: "Issue numbers, legendas e regras tipográficas" },
  "pearl-garden": { structure: "Capa jardim + carta + casal + memórias + programa + RSVP", design: "Jardim de luxo com molduras peroladas e composição assimétrica", motifs: "Pérolas, flores finas e anéis orgânicos" },
  "capulana-contemporary": { structure: "Capa têxtil + família + história + momentos + cerimónias + RSVP", design: "Editorial moçambicano contemporâneo com diagonais e módulos de tecido", motifs: "Capulana, costura, selos e padrões geométricos" },
  "celestial-ivory": { structure: "Capa celestial + palavra + countdown + casal + constelação + RSVP", design: "Luxury minimal com mapa estelar e espaço negativo", motifs: "Órbitas, constelações e microestrelas" },
  "coastal-blue": { structure: "Capa destino + localização + casal + galeria + agenda + RSVP", design: "Coastal editorial com fotografia panorâmica e ritmo de viagem", motifs: "Ondas, coordenadas e linhas de costa" },
  "aquarela-botanica": { structure: "Capa aguarela + palavra + casal + história + galeria + programa + RSVP", design: "Botânico pintado à mão com camadas de aguarela e fotografia suave", motifs: "Manchas de tinta, folhas, flores e pinceladas" },
};

const DEFAULT_DIRECTION: TemplateDirection = {
  structure: "Capa + história + programa + galeria + RSVP + entrega",
  design: "Editorial premium com composição equilibrada",
  appearance: "Minimalismo luxuoso com fotografia e detalhes refinados",
  typography: "Serif editorial + sans contemporânea",
  palette: "Neutros sofisticados com uma cor de assinatura",
  motifs: "Linhas finas, selos e detalhes gráficos discretos",
};

export function getTemplateDirection(template: TemplateDefinition): TemplateDirection {
  const source = template.value + " " + template.label + " " + template.family;
  const base = DIRECTIONS.find(({ match }) => match.test(source))?.direction ?? DEFAULT_DIRECTION;
  return { ...base, ...(TEMPLATE_DIRECTION_OVERRIDES[template.value] ?? {}) };
}
