/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugConfirmacoesRouteImport } from './routes/$slug.confirmacoes'
import { Route as SlugHomeRouteImport } from './routes/$slug.home'
import { Route as SlugImprimirRouteImport } from './routes/$slug.imprimir'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ModelosTemplateRouteImport } from './routes/modelos.$template'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const SlugConfirmacoesRoute = SlugConfirmacoesRouteImport.update({
  id: '/confirmacoes',
  path: '/confirmacoes',
  getParentRoute: () => SlugRoute,
} as any)
const SlugHomeRoute = SlugHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SlugRoute,
} as any)
const SlugImprimirRoute = SlugImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => SlugRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ModelosTemplateRoute = ModelosTemplateRouteImport.update({
  id: '/$template',
  path: '/$template',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/auth': typeof AuthRoute
  '/modelos': typeof ModelosRoute
  '/$slug/confirmacoes': typeof SlugConfirmacoesRoute
  '/$slug/home': typeof SlugHomeRoute
  '/$slug/imprimir': typeof SlugImprimirRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/modelos/$template': typeof ModelosTemplateRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/modelos': typeof ModelosRoute
  '/$slug/confirmacoes': typeof SlugConfirmacoesRoute
  '/$slug/home': typeof SlugHomeRoute
  '/$slug/imprimir': typeof SlugImprimirRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/modelos/$template': typeof ModelosTemplateRoute
  '/$slug': typeof SlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRouteWithChildren
  '/auth': typeof AuthRoute
  '/modelos': typeof ModelosRoute
  '/$slug/confirmacoes': typeof SlugConfirmacoesRoute
  '/$slug/home': typeof SlugHomeRoute
  '/$slug/imprimir': typeof SlugImprimirRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/modelos/$template': typeof ModelosTemplateRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/modelos'
    | '/$slug/confirmacoes'
    | '/$slug/home'
    | '/$slug/imprimir'
    | '/admin'
    | '/modelos/$template'
    | '/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/modelos'
    | '/$slug/confirmacoes'
    | '/$slug/home'
    | '/$slug/imprimir'
    | '/admin'
    | '/modelos/$template'
    | '/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/modelos'
    | '/$slug/confirmacoes'
    | '/$slug/home'
    | '/$slug/imprimir'
    | '/_authenticated/admin'
    | '/modelos/$template'
    | '/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRouteWithChildren
  AuthRoute: typeof AuthRoute
  ModelosRoute: typeof ModelosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/confirmacoes': {
      id: '/$slug/confirmacoes'
      path: '/confirmacoes'
      fullPath: '/$slug/confirmacoes'
      preLoaderRoute: typeof SlugConfirmacoesRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/home': {
      id: '/$slug/home'
      path: '/home'
      fullPath: '/$slug/home'
      preLoaderRoute: typeof SlugHomeRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/imprimir': {
      id: '/$slug/imprimir'
      path: '/imprimir'
      fullPath: '/$slug/imprimir'
      preLoaderRoute: typeof SlugImprimirRouteImport
      parentRoute: typeof SlugRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/modelos/$template': {
      id: '/modelos/$template'
      path: '/$template'
      fullPath: '/modelos/$template'
      preLoaderRoute: typeof ModelosTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SlugRouteChildren {
  SlugConfirmacoesRoute: typeof SlugConfirmacoesRoute
  SlugHomeRoute: typeof SlugHomeRoute
  SlugImprimirRoute: typeof SlugImprimirRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugConfirmacoesRoute: SlugConfirmacoesRoute,
  SlugHomeRoute: SlugHomeRoute,
  SlugImprimirRoute: SlugImprimirRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRouteWithChildren,
  AuthRoute: AuthRoute,
  ModelosRoute: ModelosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
